# Generated by Django 5.0 on 2023-12-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Triangle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side1', models.IntegerField()),
                ('side2', models.IntegerField()),
                ('side3', models.IntegerField()),
            ],
        ),
    ]
